name: CI Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display a message
        run: echo "Priveet, Is it really working??"

      - name: Gather System Information
        run: 
          echo "System Information:"
          lscpu
          free -h
          df -h
